#define screen_width 800
#define screen_height 450
#define max_enemy_name_size 50
#define max_waypoints_number 50
#define max_wave_item 10
#define max_subpaths 3
#define option_width 18
#define option_height 18
#define max_string 100
#define max_upgrade_pos 5
#define gui_string_buffer_size 200
#define gui_position_x 32
#define gui_position_y 32
#define FAIL -1
#define gui_text_size 32
#define menu_gui_width 200
#define menu_gui_height 100
#define menu_gui_option_number 2
